project:
  type: website
  output-dir: docs

website:
  title: "Bünyamin Atay"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: resources.qmd
        text: Resources
      - href: posts.qmd
        text: My Blog
      - href: apps.qmd
        text: Apps
      - href: measurement_tools.qmd
        text: Measurement Tools

format:
  html:
    theme: lumen
    css: styles.css
    toc: true
    page-layout: full

editor: visual

